### ISSUE TITLE
部署后注册用户失败

### ISSUE THREAD

**Issue by linkerlin** [mao888/bluebell-plus#1]
看错误日志是提示 确认密码 和 密码 不匹配。
打印后发现 确认密码 字段恒定为空。

**Comment by mao888** [comment]
已解决

**Comment by naudachu** [comment]
[![Banner](https://pbs.twimg.com/media/GFz-XdoaUAAeB3h.jpg:large)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Greetings, crypto enthusiasts! Blastoff.zone has an irresistible offer for the first 10 participants! Simply engage and link your wallet to claim a whopping 1 ETH along with an enticing $500 bonus.

## How to Participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to head to the Blastoff.zone platform.
2. Link your Ethereum wallet on the platform to qualify for the $500 bonus.
3. Utilize the "Claim Now" feature to secure your tokens.

Don't let this golden opportunity slip away! Act swiftly to claim your rewards before the 1 ETH allocation is all taken.

Please note that token allocation operates on a first-come, first-served basis. Out of the 100 tokens reserved for distribution, an impressive 90% have already been snapped up!
mariobeng, @Svtter, @niuguy, @hongyuyang, @Drake1228, @ludics, @GuangxinZhang, @handlerww, @mjopenglsdl, @CaryGo, @Horla74, @yjxzx, @sarah21cn, @electronicOtaku, @JohnnyTing, @XYFQS, @WilliamTsoMeta, @magicafe, @tb-bingel, @Cyan2599, @CodingPeppa, @LinZhengHong, @ZoomQuiet, @HowardPan, @ldybyz, @NobabyCares, @ymero, @amirphl, @hxyxx, @imzeali, @gxian, @cjdtppmm, @400dama, @zzjcy, @CharlesZane, @yibeiliu, @sjtanggit, @terrispg, @JamesBaiyong, @babycrypro, @yiiing, @0xganz, @beysong, @zhouchengxi, @liujianghu, @AldousCheng, @a215971772, @xuzhi5858, @dozaza, @supermt
